import { Injectable } from '@angular/core';
import { Application } from 'src/models/Application';

@Injectable({
  providedIn: 'root'
})
export class ApplicationService {

  constructor() { }
  public application: Application[] = [{
    id: 1,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },


  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 1,
    candidate: {
      id: 1,
      name: "pacos",
      surname: "ramir",
      description: "prueba2",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },


  {
    id: 1,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },


  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 1,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },


  {
    id: 1,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },


  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 1,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  }, 
  
  
  {
    id: 1,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },


  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 1,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  }, 
  
  
  
  {
    id: 1,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },


  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 1,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },


  {
    id: 1,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },


  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 1,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },



  {
    id: 2,
    candidate: {
      id: 1,
      name: "paco",
      surname: "ramir",
      description: "prueba1",
      status: { id: 1, name: "true" },
      contactMethod: { id: 1, name: "telefono" },
      cvDate: new Date(),
      interviewDate: new Date(),
      technicalTestDate: new Date(),
      firstContactDate: new Date(),
    },
    position: {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    status: { id: 1, name: "true" },
    rejectionReason: "Reason1",
    description: "descriptionn",
  },
  ]
}
