import { Injectable } from '@angular/core';
import { Candidate } from 'src/models/Candidate';

@Injectable({
  providedIn: 'root'
})
export class CandidateService {

  constructor() { }

  public candidates: Candidate[] = [{
    id: 1,
    name: "paco",
    surname: "ramir",
    description: "prueba1",
    status:{ id: 1, name: "true" },
    contactMethod: { id: 1, name: "telefono" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 2,
    name: "juan",
    surname: "sanc",
    description: "prueba2",
    status:{ id: 1, name: "false" },
    contactMethod: { id: 1, name: "email" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 1,
    name: "paco",
    surname: "ramir",
    description: "prueba1",
    status:{ id: 1, name: "true" },
    contactMethod: { id: 1, name: "telefono" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 2,
    name: "juan",
    surname: "sanc",
    description: "prueba2",
    status:{ id: 1, name: "false" },
    contactMethod: { id: 1, name: "email" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 1,
    name: "paco",
    surname: "ramir",
    description: "prueba1",
    status:{ id: 1, name: "true" },
    contactMethod: { id: 1, name: "telefono" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 2,
    name: "juan",
    surname: "sanc",
    description: "prueba2",
    status:{ id: 1, name: "false" },
    contactMethod: { id: 1, name: "email" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 1,
    name: "paco",
    surname: "ramir",
    description: "prueba1",
    status:{ id: 1, name: "true" },
    contactMethod: { id: 1, name: "telefono" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 2,
    name: "juan",
    surname: "sanc",
    description: "prueba2",
    status:{ id: 1, name: "false" },
    contactMethod: { id: 1, name: "email" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 1,
    name: "paco",
    surname: "ramir",
    description: "prueba1",
    status:{ id: 1, name: "true" },
    contactMethod: { id: 1, name: "telefono" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 2,
    name: "juan",
    surname: "sanc",
    description: "prueba2",
    status:{ id: 1, name: "false" },
    contactMethod: { id: 1, name: "email" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 1,
    name: "paco",
    surname: "ramir",
    description: "prueba1",
    status:{ id: 1, name: "true" },
    contactMethod: { id: 1, name: "telefono" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 2,
    name: "juan",
    surname: "sanc",
    description: "prueba2",
    status:{ id: 1, name: "false" },
    contactMethod: { id: 1, name: "email" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 1,
    name: "paco",
    surname: "ramir",
    description: "prueba1",
    status:{ id: 1, name: "true" },
    contactMethod: { id: 1, name: "telefono" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 2,
    name: "juan",
    surname: "sanc",
    description: "prueba2",
    status:{ id: 1, name: "false" },
    contactMethod: { id: 1, name: "email" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 1,
    name: "paco",
    surname: "ramir",
    description: "prueba1",
    status:{ id: 1, name: "true" },
    contactMethod: { id: 1, name: "telefono" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },
  {
    id: 2,
    name: "juan",
    surname: "sanc",
    description: "prueba2",
    status:{ id: 1, name: "false" },
    contactMethod: { id: 1, name: "email" },
    cvDate: new Date(),
    interviewDate: new Date(),
    technicalTestDate: new Date(),
    firstContactDate: new Date(),
  },

  ]
}
