import { Injectable } from '@angular/core';
import {Position} from "../../models/Position";
import { Observable, throwError } from 'rxjs';
import { HttpClient } from '@angular/common/http';
import { catchError } from 'rxjs/operators';
import { environment } from 'src/environments/environment';
import { Response } from 'src/models/Response';
@Injectable({
  providedIn: 'root'
})
export class PositionService {

  constructor(private http : HttpClient) { }

  getAll(): Observable<Response<Position[]>> {
    return this.http.get<Response<Position[]>>(`${environment.api.baseUrl}${environment.api.endpoints.position.getAllPositions}`)
      .pipe(
        catchError(this.handleError)
      );
  }

  create(position : Position): Observable<Response<Position>> {
    return this.http.post<Response<Position>>(`${environment.api.baseUrl}${environment.api.endpoints.position.create}`,position)
      .pipe(
        catchError(this.handleError)
      );
  }

  getById(id: number): Observable<Response<Position>> {
    const url = `${environment.api.baseUrl}${environment.api.endpoints.position.get}${id}`;
    return this.http.get<Response<Position>>(url)
      .pipe(
        catchError(this.handleError)
      );
  }

  delete(position: Position): Observable<Response<Position>> {
    const url = `${environment.api.baseUrl}${environment.api.endpoints.position.delete}${position.id}`;
    return this.http.delete<Response<Position>>(url)
      .pipe(
        catchError(this.handleError)
      );
  }

  update(position: Position): Observable<Response<Position>> {
    return this.http.put<Response<Position>>(`${environment.api.baseUrl}${environment.api.endpoints.position.update}`, position	)
      .pipe(
        catchError(this.handleError)
      );
  }
  private handleError(error: any): Observable<never> {
    console.error('Ha ocurrido un error:', error);
    return throwError('Error en el servicio. Por favor, inténtalo de nuevo más tarde.');
  }


  public positions: Position[] = [{
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date("2020-01-01"),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    },
    {
      id: 1,
      project: { id: 1, name: "Project A" },
      area: { id: 1, name: "Area 1" },
      rol: { id: 1, name: "Role 1" },
      subRol: { id: 1, name: "Sub Role 1" },
      localization: { id: 1, name: "Localization 1" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 1",
      vacancies: 2,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date(),
    },
    {
      id: 2,
      project: { id: 2, name: "Project B" },
      area: { id: 2, name: "Area 2" },
      rol: { id: 2, name: "Role 2" },
      subRol: { id: 2, name: "Sub Role 2" },
      localization: { id: 2, name: "Localization 2" },
      status: { id: 2, name: "Status 2" },
      description: "Position description 2",
      vacancies: 1,
      creationDate: new Date(),
      closingDate: new Date(),
      lastUpdate: new Date()
    }]
}
